
services:
  app:
    build:
      context: .
      args:
        - ENVIRONMENT=local
    ports:
      - "8080:8080"
    entrypoint: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    volumes:
      - ./app:/usr/src/app
      - ./models:/usr/src/models
    environment:
      - db_postgres_host=postgresql://sharma:sharma@sharmadb:5432/sharmabe
    depends_on:
      - sharmadb

  sharmadb:
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env-local
    volumes:
      - pgdb:/var/lib/postgresql/data

volumes:
  pgdb: