
services:
  app:
    build:
      context: .
      args:
        - ENVIRONMENT=local
    ports:
      - "8080:8080"
    entrypoint: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    volumes:
      - ./app:/usr/src/app